jobs:
  - template: default.yml@templates
    parameters:
      minrust: <false | rust version> = 1.53.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: rs3
