### POST request
POST http://localhost:5000/insert
Content-Type: application/json

{
  "code": "Deno.core.ops();Deno.core.opSync(\"rs3_list\",\"\").toString();"
}

### PATCH request execute code
PATCH http://localhost:5000/key/code

### GET request list
GET http://localhost:5000/list

### GET request get value of key
GET http://localhost:5000/key/code
